//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDX.Api.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectConversion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectConversion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDX.Api.Tests.ProjectConversion", typeof(ProjectConversion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DocumentDef Name=&quot;Document1&quot; DocVer=&quot;1&quot;&gt;
        ///			&lt;RecordDefs&gt;
        ///				&lt;RecordDef Name=&quot;Record1&quot; DesignLeft=&quot;20&quot; DesignTop=&quot;20&quot; DesignWidth=&quot;300&quot; DesignHeight=&quot;125&quot; MaxRecs=&quot;0&quot; MinRecs=&quot;0&quot;&gt;
        ///					&lt;FieldDefs&gt;
        ///						&lt;FieldDef Name=&quot;Field1&quot; AllowFlag=&quot;True&quot; DataLen=&quot;20&quot; DataType=&quot;dtText&quot; MustComplete=&quot;False&quot; OCRAllowedErrors=&quot;10&quot; OCRConfidence=&quot;75&quot; OCRRepairMode=&quot;rmNone&quot; OCRName=&quot;Field1&quot; OCRLine=&quot;0&quot; NumericShift=&quot;False&quot; QIOption=&quot;qiNonCritical&quot; UpperCase=&quot;True&quot;&gt;
        ///							&lt;AccumulatorCalc Enabled=&quot;True&quot; Accumulator=&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Accum {
            get {
                return ResourceManager.GetString("Accum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AddressCorrection Enabled=&quot;True&quot; ErrorType=&quot;etFailure&quot; ViewModes=&quot;vmFullForm,vmField,vmPhotoStitch&quot; ReviewResults=&quot;True&quot; UseDPV=&quot;True&quot;&gt;
        ///								&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///								&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///								&lt;LookupFields AddressField=&quot;Document1.Record1.Field1&quot; CityField=&quot;Document1.Record1.Field2&quot; ZipCodeField=&quot;Document1.Record1.Field1&quot;/&gt;
        ///								&lt;ResultFields AddressField=&quot;Document1.Record1.Field1&quot; CityField=&quot;Document1.Record1.Field2&quot; StateField=&quot;Document1.Record1.Field2&quot; ZipCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddressCorrection {
            get {
                return ResourceManager.GetString("AddressCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ConditionalGoto Enabled=&quot;True&quot; ErrorType=&quot;etFailure&quot; ViewModes=&quot;vmFullForm,vmField,vmPhotoStitch&quot;&gt;
        ///								&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///								&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///								&lt;Gotos&gt;
        ///									&lt;ConditionalGoto Control=&quot;Document1.Form1.TextBox2&quot; Expression=&quot;True&quot; Release=&quot;True&quot; ClearFields=&quot;True&quot;/&gt;
        ///								&lt;/Gotos&gt;
        ///							&lt;/ConditionalGoto&gt;.
        /// </summary>
        internal static string ConditionalGoto {
            get {
                return ResourceManager.GetString("ConditionalGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;10/10/01 12:35:00 AM&quot; DateModified=&quot;10/10/01 12:35:00 AM&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;True&quot; DownloadZipDB=&quot;True&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;Databases&gt;
        ///		&lt;Database Name=&quot;Database1&quot; ConnectionString=&quot;Conn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DateEdit Enabled=&quot;True&quot; ErrorType=&quot;etFailure&quot; ViewModes=&quot;vmFullForm,vmField,vmPhotoStitch&quot; AllowFutureDates=&quot;True&quot;&gt;
        ///								&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///								&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///							&lt;/DateEdit&gt;.
        /// </summary>
        internal static string DateEdit {
            get {
                return ResourceManager.GetString("DateEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DEGridDef Name=&quot;DEGrid1&quot; DataRecord=&quot;HCFA.Header.Detail&quot; KeyOrder=&quot;13&quot; TabStop=&quot;False&quot;&gt;
        ///							&lt;Colors ENGLISH=&quot;clBtnFace&quot;/&gt;
        ///							&lt;Columns&gt;
        ///								&lt;Column Name=&quot;Column1&quot; Field=&quot;HCFA.Header.Detail.od_from_date&quot;&gt;
        ///									&lt;Titles ENGLISH=&quot;From Date&quot;/&gt;
        ///									&lt;Widths ENGLISH=&quot;94&quot;/&gt;
        ///									&lt;Scripts&gt;
        ///										&lt;EventScript Name=&quot;OnValidate&quot; ScriptType=&quot;stProcedure&quot; Enabled=&quot;True&quot;&gt;
        ///											&lt;Script&gt;
        ///												&lt;String Value=&quot;procedure OnValidate(TextBox: ScriptTextBox);&quot;/&gt;
        ///												&lt;String [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DEGridDef {
            get {
                return ResourceManager.GetString("DEGridDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DEGridDef Name=&quot;DEGrid1&quot; DataRecord=&quot;HCFA.Header.Detail&quot; KeyOrder=&quot;13&quot; TabStop=&quot;False&quot; /&gt;.
        /// </summary>
        internal static string DEGridHeaderHeight {
            get {
                return ResourceManager.GetString("DEGridHeaderHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DEGridDef Name=&quot;DEGrid1&quot; DataRecord=&quot;HCFA.Header.Detail&quot; KeyOrder=&quot;13&quot; TabStop=&quot;False&quot;&gt;
        ///							&lt;Columns&gt;
        ///								&lt;Column Name=&quot;Column1&quot;&gt;
        ///									&lt;Titles ENGLISH=&quot;From Date&quot;/&gt;
        ///									&lt;Widths ENGLISH=&quot;94&quot;/&gt;
        ///								&lt;/Column&gt;
        ///								&lt;Column Name=&quot;Column2&quot;&gt;
        ///									&lt;Titles ENGLISH=&quot;To Date&quot;/&gt;
        ///									&lt;Widths ENGLISH=&quot;94&quot;/&gt;
        ///								&lt;/Column&gt;
        ///&lt;/Columns&gt;
        ///&lt;/DEGridDef&gt;.
        /// </summary>
        internal static string DEGridTextBoxKeyOrder {
            get {
                return ResourceManager.GetString("DEGridTextBoxKeyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DetailGridDef Name=&quot;DetailGrid1&quot; DataRecord=&quot;Document1.Record1.Record2&quot; KeyOrder=&quot;3&quot; Options=&quot;dgRestrictExit&quot; Rows=&quot;6&quot; ShowHeader=&quot;True&quot; ShowRecordNumber=&quot;srRight&quot; TabStop=&quot;True&quot;&gt;
        ///							&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///							&lt;Colors ENGLISH=&quot;clBtnFace&quot;/&gt;
        ///							&lt;Fonts&gt;
        ///								&lt;Font Name=&quot;ENGLISH&quot; Charset=&quot;1&quot; Color=&quot;clWindowText&quot; Height=&quot;-17&quot; FontName=&quot;Courier New&quot; Pitch=&quot;fpDefault&quot;/&gt;
        ///							&lt;/Fonts&gt;
        ///							&lt;HeaderColors ENGLISH=&quot;clBackground&quot;/&gt;
        ///							&lt;HeaderFonts&gt;
        ///								&lt;Font Name=&quot;ENGLISH&quot; Cha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailGrid {
            get {
                return ResourceManager.GetString("DetailGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-07-20T09:04:12.765-06:00&quot; DateModified=&quot;2006-07-28T15:16:32.812-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailZoneEmpty {
            get {
                return ResourceManager.GetString("DetailZoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-07-20T09:04:12.765-06:00&quot; DateModified=&quot;2006-07-28T15:09:12.484-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailZoneNone {
            get {
                return ResourceManager.GetString("DetailZoneNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-07-20T09:04:12.765-06:00&quot; DateModified=&quot;2007-04-24T11:17:00.200-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailZoneNormal {
            get {
                return ResourceManager.GetString("DetailZoneNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-07-20T09:04:12.765-06:00&quot; DateModified=&quot;2006-08-15T15:27:37.968-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailZoneNoSubs {
            get {
                return ResourceManager.GetString("DetailZoneNoSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-07-20T09:04:12.765-06:00&quot; DateModified=&quot;2006-07-28T15:22:36.171-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailZoneRegularZone {
            get {
                return ResourceManager.GetString("DetailZoneRegularZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DiagnosisPtr Enabled=&quot;True&quot; ErrorType=&quot;etIgnore&quot; ViewModes=&quot;vmFullForm,vmField,vmPhotoStitch&quot; Database=&quot;Test&quot; Query=&quot;QUERY&quot;&gt;
        ///								&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///								&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///								&lt;DiagnosisCodes&gt;
        ///									&lt;DiagCodeFields Field=&quot;Document1.Record1.Field1&quot;/&gt;
        ///									&lt;DiagCodeFields Field=&quot;Document1.Record1.Field2&quot;/&gt;
        ///									&lt;DiagCodeFields Field=&quot;Document1.Record1.Field1&quot;/&gt;
        ///									&lt;DiagCodeFields Field=&quot;Document1.Record1.Field2&quot;/&gt;
        ///									&lt;DiagCodeFields  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiagnosisPtr {
            get {
                return ResourceManager.GetString("DiagnosisPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Document1&quot; StoredDocType=&quot;StoredDocType&quot; DocVer=&quot;1&quot;&gt;
        ///			&lt;Accumulators&gt;
        ///				&lt;Accumulator Name=&quot;Accum1&quot; ErrorMargin=&quot;0&quot; ErrorType=&quot;etFailure&quot;&gt;
        ///					&lt;ErrorMessages ENGLISH=&quot;ErrorMessage&quot;/&gt;
        ///				&lt;/Accumulator&gt;
        ///			&lt;/Accumulators&gt;
        ///			&lt;Descriptions ENGLISH=&quot;Description&quot;/&gt;
        ///			&lt;RejectCodes&gt;
        ///				&lt;RejectCodeLink RejectCode=&quot;01&quot;/&gt;
        ///			&lt;/RejectCodes&gt;
        ///		&lt;/DocumentDef&gt;
        ///	&lt;/DocumentDefs&gt;.
        /// </summary>
        internal static string DocumentDefs {
            get {
                return ResourceManager.GetString("DocumentDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-09-07T09:18:20.100-06:00&quot; DateModified=&quot;2006-09-07T09:18:20.100-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DuplicateRecForm {
            get {
                return ResourceManager.GetString("DuplicateRecForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EventScript Name=&quot;OnValidate&quot; ScriptType=&quot;stFunction&quot; Enabled=&quot;True&quot;&gt;
        ///									&lt;Script&gt;
        ///										&lt;String Value=&quot;function TestFunction(TextBox: ScriptTextBox);&quot;/&gt;
        ///										&lt;String Value=&quot;begin&quot;/&gt;
        ///										&lt;String Value=&quot;  WebDE.Error(&apos;This is a test error.&apos;);&quot;/&gt;
        ///										&lt;String Value=&quot;end;&quot;/&gt;
        ///									&lt;/Script&gt;
        ///								&lt;/EventScript&gt;.
        /// </summary>
        internal static string EventScript {
            get {
                return ResourceManager.GetString("EventScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var x: Integer;
        ///
        ///function OnValidate(TextBox: ScriptTextBox);
        ///begin
        ///  WebDE.Error(&apos;This is a test error.&apos;);
        ///end;
        ///.
        /// </summary>
        internal static string EventScriptResult {
            get {
                return ResourceManager.GetString("EventScriptResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDefs&gt;
        ///						&lt;FieldDef Name=&quot;Field1&quot; AllowFlag=&quot;True&quot; CharSet=&quot;A-Z&quot; DataLen=&quot;20&quot; DataType=&quot;dtText&quot; DefaultValue=&quot;DEFAULT&quot; MustComplete=&quot;True&quot; OCRAllowedErrors=&quot;10&quot; OCRCharSet=&quot;A-Z&quot; OCRConfidence=&quot;75&quot; OCRRepairMode=&quot;rmAlphaNumeric&quot; OCRName=&quot;Field1&quot; OCRLine=&quot;2&quot; NumericShift=&quot;True&quot; QIOption=&quot;qiExclude&quot; UpperCase=&quot;True&quot;&gt;
        ///							&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///							&lt;CheckDigit Enabled=&quot;True&quot; AllowZeros=&quot;True&quot; Generate=&quot;True&quot; Methods=&quot;cdMod10,cdMod7,cdVisa,cdMasterCard,cdAMEX,cdDiscover,cdDiners,cdISBN,c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FieldDefs {
            get {
                return ResourceManager.GetString("FieldDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FormDefs&gt;
        ///				&lt;FormDef Name=&quot;Form1&quot; DataRecord=&quot;Document1.Record1&quot; SelectedColor=&quot;clYellow&quot; UseSnippets=&quot;True&quot;&gt;
        ///					&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///					&lt;Colors ENGLISH=&quot;clBtnFace&quot;/&gt;
        ///					&lt;ControlDefs /&gt;
        ///					&lt;Fonts&gt;
        ///						&lt;Font Name=&quot;ENGLISH&quot; Charset=&quot;1&quot; Color=&quot;clWindowText&quot; Height=&quot;-13&quot; FontName=&quot;MS Sans Serif&quot; Pitch=&quot;fpDefault&quot;/&gt;
        ///					&lt;/Fonts&gt;
        ///					&lt;Helps ENGLISH=&quot;Help&quot;/&gt;
        ///					&lt;Hints ENGLISH=&quot;Hint&quot;/&gt;
        ///					&lt;ImageSourceLinks&gt;
        ///						&lt;ImageSourceLink Name=&quot;ImageSourceLink1&quot; ImageSource=&quot;Document1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormDefs {
            get {
                return ResourceManager.GetString("FormDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;GroupBoxDef Name=&quot;GroupBox1&quot; KeyOrder=&quot;2&quot; Options=&quot;gpRepairEntireGroup,gpClearDuringRepair&quot; TabStop=&quot;True&quot;&gt;
        ///							&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///							&lt;Captions ENGLISH=&quot;Caption&quot;/&gt;
        ///							&lt;Colors ENGLISH=&quot;clBtnFace&quot;/&gt;
        ///							&lt;Fonts&gt;
        ///								&lt;Font Name=&quot;ENGLISH&quot; Charset=&quot;1&quot; Color=&quot;clWindowText&quot; Height=&quot;-13&quot; FontName=&quot;Tahoma&quot; Pitch=&quot;fpDefault&quot;/&gt;
        ///							&lt;/Fonts&gt;
        ///							&lt;Heights ENGLISH=&quot;223&quot;/&gt;
        ///							&lt;Helps ENGLISH=&quot;Help&quot;/&gt;
        ///							&lt;Hints ENGLISH=&quot;Hint&quot;/&gt;
        ///							&lt;Lefts ENGLISH=&quot;379&quot;/&gt;
        ///							&lt;Tops [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupBox {
            get {
                return ResourceManager.GetString("GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-07-20T09:04:12.765-06:00&quot; DateModified=&quot;2006-08-14T14:57:53.914-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupBoxFlattened {
            get {
                return ResourceManager.GetString("GroupBoxFlattened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;InputSourceDefs&gt;
        ///				&lt;ImageSource Name=&quot;ImageSource1&quot; StoredAttachType=&quot;Stored&quot; Overlay=&quot;overlay&quot; PerformOCR=&quot;True&quot; Template=&quot;template&quot;&gt;
        ///					&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///				&lt;/ImageSource&gt;
        ///			&lt;/InputSourceDefs&gt;.
        /// </summary>
        internal static string ImageSourceDefs {
            get {
                return ResourceManager.GetString("ImageSourceDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LabelDef Name=&quot;Label1&quot; AutoSize=&quot;True&quot; Field=&quot;Document1.Record1.Field1&quot; NextControl=&quot;Document1.Form1.TextBox1&quot; SysData=&quot;sysNone&quot;&gt;
        ///							&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///							&lt;Alignments ENGLISH=&quot;2&quot;/&gt;
        ///							&lt;Captions ENGLISH=&quot;Field1&quot;/&gt;
        ///							&lt;Colors ENGLISH=&quot;clBtnFace&quot;/&gt;
        ///							&lt;Fonts&gt;
        ///								&lt;Font Name=&quot;ENGLISH&quot; Charset=&quot;1&quot; Color=&quot;clWindowText&quot; Height=&quot;-13&quot; FontName=&quot;Tahoma&quot; Pitch=&quot;fpDefault&quot; Style=&quot;fsBold,fsItalic,fsUnderline,fsStrikeOut&quot;/&gt;
        ///							&lt;/Fonts&gt;
        ///							&lt;Heights ENGLISH=&quot;16&quot;/&gt;
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabelDef {
            get {
                return ResourceManager.GetString("LabelDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MustEnter Enabled=&quot;True&quot; ErrorType=&quot;etFailure&quot; ViewModes=&quot;vmFullForm,vmField,vmPhotoStitch&quot; Expression=&quot;EXPR&quot;&gt;
        ///								&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///								&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///							&lt;/MustEnter&gt;.
        /// </summary>
        internal static string MustEnter {
            get {
                return ResourceManager.GetString("MustEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;$00E7FFFF&quot; CellBorderColor=&quot;clRed&quot; DateCreated=&quot;2006-07-20T09:04:12.765-06:00&quot; DateModified=&quot;2006-07-20T09:04:12.765-06:00&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;$00E7FFFF&quot; SnippetBorderColor=&quot;clRed&quot; ZoneColor=&quot;clYellow&quot; ZoneBorderColor=&quot;clRed&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.4.3&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/&gt;
        ///	&lt;/Languages&gt;
        ///	&lt;DocumentDefs&gt;
        ///		&lt;DocumentDef Name=&quot;Documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectMultiScriptConvert {
            get {
                return ResourceManager.GetString("ProjectMultiScriptConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var x = 10;
        ///function Script1();
        ///begin
        ///  Result := True;
        ///end;
        ///function Script2();
        ///begin
        ///  Result := 3;
        ///end;
        ///
        ///.
        /// </summary>
        internal static string ProjectMultiScriptResult {
            get {
                return ResourceManager.GetString("ProjectMultiScriptResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ActiveLanguage=&quot;ENGLISH&quot; CellColor=&quot;clBlack&quot; CellBorderColor=&quot;clPurple&quot; CreatedBy=&quot;Creator&quot; DateCreated=&quot;2006-02-28T15:22:24.265-07:00&quot; DateModified=&quot;2006-02-28T15:22:24.265-07:00&quot; ModifiedBy=&quot;Modifier&quot; Options=&quot;poTrackImage,poShowCharSetError&quot; ScriptLanguage=&quot;ltDelphiScript&quot; SnippetColor=&quot;clMaroon&quot; SnippetBorderColor=&quot;clOlive&quot; Version=&quot;1.0.0.0&quot; ZoneColor=&quot;clTeal&quot; ZoneBorderColor=&quot;clGray&quot; DownloadOverlays=&quot;False&quot; DownloadZipDB=&quot;False&quot; APIVersion=&quot;1.3.0.0&quot;&gt;
        ///	&lt;Languages&gt;
        ///		&lt;Language Name=&quot;ENGLISH&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectObject {
            get {
                return ResourceManager.GetString("ProjectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RecordDefs&gt;
        ///				&lt;RecordDef Name=&quot;Record1&quot; DesignLeft=&quot;20&quot; DesignTop=&quot;20&quot; DesignWidth=&quot;300&quot; DesignHeight=&quot;125&quot; MaxRecs=&quot;10&quot; MinRecs=&quot;5&quot;&gt;
        ///					&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///				&lt;/RecordDef&gt;
        ///			&lt;/RecordDefs&gt;.
        /// </summary>
        internal static string RecordDefs {
            get {
                return ResourceManager.GetString("RecordDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RejectCodes&gt;
        ///				&lt;RejectCodeLink RejectCode=&quot;01&quot;/&gt;
        ///			&lt;/RejectCodes&gt;.
        /// </summary>
        internal static string RejectCodeLinks {
            get {
                return ResourceManager.GetString("RejectCodeLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RejectCodes&gt;
        ///		&lt;RejectCode Name=&quot;01&quot; RequireDescription=&quot;False&quot;&gt;
        ///			&lt;Descriptions ENGLISH=&quot;BadScan&quot;/&gt;
        ///		&lt;/RejectCode&gt;
        ///		&lt;RejectCode Name=&quot;02&quot; RequireDescription=&quot;True&quot;&gt;
        ///			&lt;Descriptions ENGLISH=&quot;Other&quot;/&gt;
        ///		&lt;/RejectCode&gt;
        ///	&lt;/RejectCodes&gt;.
        /// </summary>
        internal static string RejectCodes {
            get {
                return ResourceManager.GetString("RejectCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableLookup Enabled=&quot;True&quot; ErrorType=&quot;etFailure&quot; ViewModes=&quot;vmFullForm,vmField,vmPhotoStitch&quot; ExecuteOn=&quot;exValidate&quot;&gt;
        ///								&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///								&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///								&lt;Lookups&gt;
        ///									&lt;TableLookup Database=&quot;Test&quot; Query=&quot;SELECT * FROM MCPUSER&quot; Options=&quot;loFailIfNoRecords,loReviewResults,loFilter,loOneHitPopup,loLookupIfBlank,loSavePos,loShowDiffs,loVerifyPluggedData&quot;&gt;
        ///										&lt;ResultFields&gt;
        ///											&lt;ResultFields DBFieldName=&quot;USE_LOGIN&quot; Field=&quot;Docume [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableLookup {
            get {
                return ResourceManager.GetString("TableLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBoxDef Name=&quot;TextBox1&quot; AllowFlag=&quot;True&quot; AutoAdvance=&quot;True&quot; CharSet=&quot;A-Z&quot; Field=&quot;Document1.Record1.Field1&quot; InputMask=&quot;{A-Z}&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&amp;amp;&quot; KeyOrder=&quot;1&quot; Options=&quot;opExcludeFromFieldRepair,opSkipVerify,opSkipQIVerify,opFieldVerify,opEntryModeInVerify&quot; ShowSnippetImage=&quot;True&quot; TabStop=&quot;True&quot;&gt;
        ///							&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///							&lt;AddressCorrection Enabled=&quot;True&quot; ErrorType=&quot;etFailure&quot; ViewModes=&quot;vmFullForm,vmField,vmPho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function Document1.Form1.TextBox1.OnValidate(TextBox: ScriptTextBox);
        ///begin
        ///  WebDE.Error(&apos;This is a test error.&apos;);
        ///end;
        ///.
        /// </summary>
        internal static string TextBoxOnValidate {
            get {
                return ResourceManager.GetString("TextBoxOnValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Validate Enabled=&quot;True&quot; ErrorType=&quot;etFailure&quot; ViewModes=&quot;vmFullForm,vmField,vmPhotoStitch&quot;&gt;
        ///								&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///								&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///								&lt;Validations&gt;
        ///									&lt;Validations Name=&quot;NAME&quot; Expression=&quot;EXPR&quot; ErrorMessage=&quot;ERROR_MESSAGE&quot;&gt;
        ///										&lt;ErrorMessages ENGLISH=&quot;ERROR_MESSAGE&quot;/&gt;
        ///									&lt;/Validations&gt;
        ///								&lt;/Validations&gt;
        ///							&lt;/Validate&gt;.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ViewDefs&gt;
        ///		&lt;ViewDef Name=&quot;DefaultView&quot; DataPanelHeight=&quot;10&quot; FirstImage=&quot;15&quot; Options=&quot;voAllowBatchReject,voAllowFloatingWindow,voReviewAllImages,voShowWorkZones,voShowOverlay,voAllowModifyNonKeyables,voAllowDocReject,voAutoSave,voAllowImageTypeChange,voAllowFieldVerify&quot; ShowTicker=&quot;True&quot; TickerCharHeight=&quot;50&quot; ScaleMode=&quot;smFitBest&quot; ScalePercent=&quot;50&quot; ViewMode=&quot;vmOnePass&quot; ViewStyle=&quot;vsVertical&quot;&gt;
        ///			&lt;Descriptions ENGLISH=&quot;DESC&quot;/&gt;
        ///			&lt;FormLinks&gt;
        ///				&lt;FormLink Form=&quot;Document1.Form1&quot;/&gt;
        ///			&lt;/FormLinks&gt;
        ///			&lt;P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewDefs {
            get {
                return ResourceManager.GetString("ViewDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DocumentDef Name=&quot;Document1&quot; DocVer=&quot;1&quot;&gt;
        ///			&lt;RecordDefs&gt;
        ///				&lt;RecordDef Name=&quot;Record1&quot; DesignLeft=&quot;20&quot; DesignTop=&quot;20&quot; DesignWidth=&quot;300&quot; DesignHeight=&quot;125&quot; MaxRecs=&quot;0&quot; MinRecs=&quot;0&quot;&gt;
        ///					&lt;FieldDefs&gt;
        ///						&lt;FieldDef Name=&quot;Field1&quot; AllowFlag=&quot;True&quot; DataLen=&quot;20&quot; DataType=&quot;dtText&quot; MustComplete=&quot;False&quot; OCRAllowedErrors=&quot;10&quot; OCRConfidence=&quot;75&quot; OCRRepairMode=&quot;rmNone&quot; OCRName=&quot;Field1&quot; OCRLine=&quot;0&quot; NumericShift=&quot;False&quot; QIOption=&quot;qiNonCritical&quot; UpperCase=&quot;True&quot;&gt;
        ///							&lt;AccumulatorCalc Enabled=&quot;True&quot; Accumulator=&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZoneLabelLinks {
            get {
                return ResourceManager.GetString("ZoneLabelLinks", resourceCulture);
            }
        }
    }
}
