//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDX.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WDEExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WDEExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDX.Api.WDEExceptionResources", typeof(WDEExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not assigned|Assign an IWDEProject to the IWDEDataSet.Project property or assign the path to the WebDX Project File to the IWDEDataSet.ProjectFile property..
        /// </summary>
        internal static string API00001 {
            get {
                return ResourceManager.GetString("API00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not defined in project|Document: {0}\nRecord: {1}\nField: {2}.
        /// </summary>
        internal static string API00002 {
            get {
                return ResourceManager.GetString("API00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status can only be set to None, Plugged, Validated or Flagged|Attempted to set a status of: {0} on Field: {1}. This status can only be set by the keyer client..
        /// </summary>
        internal static string API00003 {
            get {
                return ResourceManager.GetString("API00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in value &quot;{0}&quot;|The value {0} contains characters that don&apos;t match the CharacterSet defined for this field. Field: {1}.
        /// </summary>
        internal static string API00005 {
            get {
                return ResourceManager.GetString("API00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be completed|The length of &quot;{0}&quot; is shorter than the required length ({1}) for Field: {2}. (MustComplete Edit is enabled).
        /// </summary>
        internal static string API00006 {
            get {
                return ResourceManager.GetString("API00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set value of field to initialize field|Attempted to set the IsNull property to false on Field: {0}. Set the .Value property instead..
        /// </summary>
        internal static string API00007 {
            get {
                return ResourceManager.GetString("API00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with ID {0} missing from document {1}|The requested session was not found..
        /// </summary>
        internal static string API00009 {
            get {
                return ResourceManager.GetString("API00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field name &quot;{0}&quot;|The field was not found during Record.FieldByName.
        /// </summary>
        internal static string API00010 {
            get {
                return ResourceManager.GetString("API00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current record|Try calling First() before accessing this property or method..
        /// </summary>
        internal static string API00011 {
            get {
                return ResourceManager.GetString("API00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index out of range|Object: {0}\nIndex: {1}\nCount: {2}.
        /// </summary>
        internal static string API00012 {
            get {
                return ResourceManager.GetString("API00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid record type &quot;{0}&quot;|Attempted to append a record using a record type that is not found in DocumentDef &quot;{1}&quot;.
        /// </summary>
        internal static string API00013 {
            get {
                return ResourceManager.GetString("API00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type: &quot;{0}&quot;|The specified image type was not found in DocumentDef &quot;{1}&quot;.
        /// </summary>
        internal static string API00014 {
            get {
                return ResourceManager.GetString("API00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document type: &quot;{0}&quot;|The specified document type was not found in the project..
        /// </summary>
        internal static string API00015 {
            get {
                return ResourceManager.GetString("API00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current document|Try calling First() before accessing this property or method..
        /// </summary>
        internal static string API00016 {
            get {
                return ResourceManager.GetString("API00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current document|Add documents before accessing this property or method..
        /// </summary>
        internal static string API00017 {
            get {
                return ResourceManager.GetString("API00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current record|Add records before accessing this property or method..
        /// </summary>
        internal static string API00018 {
            get {
                return ResourceManager.GetString("API00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateData() must be called prior to Append/Insert|For a new data file, CreateData() must be called before adding documents..
        /// </summary>
        internal static string API00019 {
            get {
                return ResourceManager.GetString("API00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid root element: {0}|The root element in this xml file is not valid..
        /// </summary>
        internal static string API00020 {
            get {
                return ResourceManager.GetString("API00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName not specified|Please set the filename property before accessing this method..
        /// </summary>
        internal static string API00021 {
            get {
                return ResourceManager.GetString("API00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet not active|Please load a file or call CreateData() before calling this method..
        /// </summary>
        internal static string API00022 {
            get {
                return ResourceManager.GetString("API00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reject code &quot;{0}&quot;|The specified reject code was not found in the project..
        /// </summary>
        internal static string API00023 {
            get {
                return ResourceManager.GetString("API00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RejectCode &quot;{0}&quot; requires a description|Please set a description for this reject code..
        /// </summary>
        internal static string API00024 {
            get {
                return ResourceManager.GetString("API00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RejectCode &quot;{0}&quot; while setting RejectDescription|Please set the RejectCode property to a valid reject code before setting RejectDescription..
        /// </summary>
        internal static string API00025 {
            get {
                return ResourceManager.GetString("API00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty data file|This data file does not contain any documents. Please use CreateData to create a new data file..
        /// </summary>
        internal static string API00026 {
            get {
                return ResourceManager.GetString("API00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked object not found|The linked object {0} is not part of this project.\nRequestor: {1}.
        /// </summary>
        internal static string API00028 {
            get {
                return ResourceManager.GetString("API00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid root node in project file|The root node is named &quot;{0}&quot; and should be named &quot;Project&quot;.
        /// </summary>
        internal static string API00029 {
            get {
                return ResourceManager.GetString("API00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} owner|{0} can only be owned by {1}.
        /// </summary>
        internal static string API00030 {
            get {
                return ResourceManager.GetString("API00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not found|Linked object {0} does not contain a method called {1}.
        /// </summary>
        internal static string API00031 {
            get {
                return ResourceManager.GetString("API00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ScriptLanguage during conversion|Script language {0} is not supported when converting projects..
        /// </summary>
        internal static string API00032 {
            get {
                return ResourceManager.GetString("API00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property not found|Linked object {0} does not contain a property called {1}.
        /// </summary>
        internal static string API00033 {
            get {
                return ResourceManager.GetString("API00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid imagelink format {0}|The imagelink format should be Document.Form.ImageLinkName.ZoneName..
        /// </summary>
        internal static string API00034 {
            get {
                return ResourceManager.GetString("API00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not defined in project|Document: {0}\nRecord: {1}.
        /// </summary>
        internal static string API00035 {
            get {
                return ResourceManager.GetString("API00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No FormLinks in SessionDef|SessionDef &quot;{0}&quot; contains no FormLinks..
        /// </summary>
        internal static string API00036 {
            get {
                return ResourceManager.GetString("API00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in name|The name &quot;{0}&quot; contains invalid characters.\nValid names can contain only upper and lower case letters, numbers and underscores.\nNames cannot begin with anything other than a letter..
        /// </summary>
        internal static string API00037 {
            get {
                return ResourceManager.GetString("API00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name|An object with the name &quot;{0}&quot; is already in this project..
        /// </summary>
        internal static string API00038 {
            get {
                return ResourceManager.GetString("API00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching document in SessionDef|SessionDef &quot;{0}&quot; does not have a form from document &quot;{1}&quot; which contains image type &quot;{2}&quot;.
        /// </summary>
        internal static string API00039 {
            get {
                return ResourceManager.GetString("API00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target version.|The target API version {0} is invalid..
        /// </summary>
        internal static string API00040 {
            get {
                return ResourceManager.GetString("API00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Edit Def &quot;{0}&quot;|The edit def passed to edit &quot;{1}&quot; does not implement the required interface &quot;{2}&quot;.
        /// </summary>
        internal static string API70001 {
            get {
                return ResourceManager.GetString("API70001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Definition Error|Invalid parameter definition in edit {0}, parameter {1}: {2}.
        /// </summary>
        internal static string API70002 {
            get {
                return ResourceManager.GetString("API70002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script host object unavailable.|The script host object &quot;{0}&quot; is not available at this time..
        /// </summary>
        internal static string API80001 {
            get {
                return ResourceManager.GetString("API80001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CharRepairs can&apos;t be accessed without a current revision|This is an internal error. Please contact the WebDX support team. Field: {0}.
        /// </summary>
        internal static string API90001 {
            get {
                return ResourceManager.GetString("API90001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found in collection {0}|This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90002 {
            get {
                return ResourceManager.GetString("API90002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions not initialized|This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90003 {
            get {
                return ResourceManager.GetString("API90003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet is null|This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90004 {
            get {
                return ResourceManager.GetString("API90004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkResolver not set|This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90005 {
            get {
                return ResourceManager.GetString("API90005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopParent not defined for object {0}|This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90006 {
            get {
                return ResourceManager.GetString("API90006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ICloneable|Linked object {0} does not implement the ICloneable interface. This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90007 {
            get {
                return ResourceManager.GetString("API90007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent is not {0} for object {1}|This is an internal error. Please contact the WebDX Support Team..
        /// </summary>
        internal static string API90008 {
            get {
                return ResourceManager.GetString("API90008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to link object|This is an internal error. Please contact the WebDX support team.\nRequesting object: {0}\nRequesting property: {1}\nRequested object: {2}\nOriginal exception: {3}.
        /// </summary>
        internal static string API90009 {
            get {
                return ResourceManager.GetString("API90009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to invoke link method|This is an internal error. Please contact the WebDX support team.\nRequesting object: {0}\nRequesting method: {1}\nOriginal exception: {2}.
        /// </summary>
        internal static string API90010 {
            get {
                return ResourceManager.GetString("API90010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set override property value during dupe|This is an internal error. Please contact the WebDX support team.\nRequesting object: {0}\nRequesting property: {1}\nNew value: {2}\nOriginal exception: {3}.
        /// </summary>
        internal static string API90011 {
            get {
                return ResourceManager.GetString("API90011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to invoke link method during dupe|This is an internal error. Please contact the WebDX support team.\nRequesting object: {0}\nRequesting method: {1}\nRequested object: {2}\nOriginal exception: {3}.
        /// </summary>
        internal static string API90012 {
            get {
                return ResourceManager.GetString("API90012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone not owned by ImageSourceDef|This is an internal error. Please contact the WebDX support team.\nZone name: {0}.
        /// </summary>
        internal static string API90013 {
            get {
                return ResourceManager.GetString("API90013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not owned by {1}|This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90014 {
            get {
                return ResourceManager.GetString("API90014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormDef not found in document collection|FormDef &quot;{0}&quot; not found in document collection. This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90015 {
            get {
                return ResourceManager.GetString("API90015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} was lost in the {2} with {3} = {4} where {0} = {5}|This is an internal error. Please contact the WebDX support team..
        /// </summary>
        internal static string API90016 {
            get {
                return ResourceManager.GetString("API90016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error Code|This error code is not known to the system..
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
    }
}
