//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDX.Api.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectExpectedResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectExpectedResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDX.Api.Tests.ProjectExpectedResults", typeof(ProjectExpectedResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AddressCorrectionEditDef DisplayName=&quot;AddressCorrection&quot; Enabled=&quot;True&quot; FullName=&quot;ACS.WebDE.Edits.AddressCorrection&quot; ReviewResults=&quot;True&quot; UseDPV=&quot;True&quot;&gt;
        ///  &lt;LookupFields CityField=&quot;Document1.Record1.Field1&quot; /&gt;
        ///  &lt;ResultFields StateField=&quot;Document1.Record1.Field2&quot; /&gt;
        ///&lt;/AddressCorrectionEditDef&gt;.
        /// </summary>
        internal static string AddressCorrEditDefWTX {
            get {
                return ResourceManager.GetString("AddressCorrEditDefWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ConditionalGotoEditDef&gt;
        ///  &lt;Goto Control=&quot;Document1.Form1.TextBox1&quot; Expression=&quot;Expression1&quot; ClearFields=&quot;True&quot; /&gt;
        ///  &lt;Goto Expression=&quot;Expression2&quot; Release=&quot;True&quot; ClearFields=&quot;True&quot; /&gt;
        ///&lt;/ConditionalGotoEditDef&gt;.
        /// </summary>
        internal static string ConditionalGotoEditDefWTX {
            get {
                return ResourceManager.GetString("ConditionalGotoEditDefWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LabelDef ControlName=&quot;Label1&quot; Font=&quot;Tahoma, 10pt&quot; /&gt;
        ///&lt;TextBoxDef ControlName=&quot;TextBox1&quot; Font=&quot;Tahoma, 10pt&quot;&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt;ScriptDef /&gt;
        ///&lt;/TextBoxDef&gt;
        ///&lt;GroupBoxDef ControlName=&quot;GroupBox1&quot; Font=&quot;Tahoma, 10pt&quot; /&gt;
        ///&lt;DetailGridDef ControlName=&quot;DetailGrid1&quot; Font=&quot;Tahoma, 10pt&quot; HeaderFont=&quot;Tahoma, 10pt&quot;&gt;
        ///  &lt;Header /&gt;
        ///  &lt;Detail /&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt;ScriptDef /&gt;
        ///&lt;/DetailGridDef&gt;.
        /// </summary>
        internal static string ControlDefsWTX {
            get {
                return ResourceManager.GetString("ControlDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DetailGridDef BackColor=&quot;Red&quot; Description=&quot;Description1&quot; Help=&quot;Help1&quot; Hint=&quot;Hint1&quot; KeyOrder=&quot;10&quot; TabStop=&quot;True&quot; Location=&quot;10,20,40,60&quot; ControlName=&quot;DetailGrid1&quot; Font=&quot;Tahoma, 10pt&quot; HeaderHeight=&quot;10&quot; HeaderFont=&quot;Tahoma, 10pt&quot; HeaderBackColor=&quot;Blue&quot; HeaderForeColor=&quot;Black&quot; Options=&quot;RestrictExit&quot; Rows=&quot;10&quot; RecordNumberPosition=&quot;Left&quot; RecordDef=&quot;Document1.Record1&quot;&gt;
        ///  &lt;Header /&gt;
        ///  &lt;Detail /&gt;
        ///  &lt;ScriptDef Description=&quot;OnEnter Description&quot; Enabled=&quot;True&quot; ScriptFullName=&quot;ScriptFullName&quot; /&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailGridDefWTX {
            get {
                return ResourceManager.GetString("DetailGridDefWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DetailZoneDef DetailZoneName=&quot;DetailZone1&quot; LineCount=&quot;6&quot; LineHeight=&quot;150&quot;&gt;
        ///  &lt;ZoneDef ZoneName=&quot;Zone1&quot; /&gt;
        ///  &lt;ZoneDef ZoneName=&quot;Zone2&quot; /&gt;
        ///&lt;/DetailZoneDef&gt;
        ///&lt;DetailZoneDef DetailZoneName=&quot;DetailZone2&quot; /&gt;.
        /// </summary>
        internal static string DetailZonesWTX {
            get {
                return ResourceManager.GetString("DetailZonesWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DiagnosisPtrEditDef Database=&quot;Database1&quot; Query=&quot;Query1&quot;&gt;
        ///  &lt;FieldDefLink Name=&quot;Document1.Record1.Field1&quot; /&gt;
        ///  &lt;FieldDefLink Name=&quot;Document1.Record1.Field2&quot; /&gt;
        ///&lt;/DiagnosisPtrEditDef&gt;.
        /// </summary>
        internal static string DiagnosisPtrWTX {
            get {
                return ResourceManager.GetString("DiagnosisPtrWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DocumentDef DocType=&quot;Document1&quot; Description=&quot;Description1&quot; StoredDocType=&quot;StoredDocType1&quot; /&gt;
        ///&lt;DocumentDef DocType=&quot;Document2&quot; /&gt;.
        /// </summary>
        internal static string DocumentDefsWTX {
            get {
                return ResourceManager.GetString("DocumentDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AddressCorrectionEditDef DisplayName=&quot;AddressCorrection&quot; FullName=&quot;ACS.WebDE.AddressCorrection&quot;&gt;
        ///  &lt;LookupFields /&gt;
        ///  &lt;ResultFields /&gt;
        ///&lt;/AddressCorrectionEditDef&gt;
        ///&lt;CheckDigitEditDef /&gt;
        ///&lt;ConditionalGotoEditDef /&gt;
        ///&lt;DateEditDef /&gt;
        ///&lt;DiagnosisPtrEditDef /&gt;
        ///&lt;RangeEditDef /&gt;
        ///&lt;RequiredEditDef /&gt;
        ///&lt;SimpleListEditDef /&gt;
        ///&lt;TableLookupEditDef /&gt;
        ///&lt;ValidLengthsEditDef /&gt;.
        /// </summary>
        internal static string EditDefsWTX {
            get {
                return ResourceManager.GetString("EditDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EditDef DisplayName=&quot;AddressCorrection&quot; FullName=&quot;ACS.WebDE.Edits.AddressCorrection&quot;&gt;&lt;![CDATA[&lt;AddressCorrectionEditDef DisplayName=&quot;AddressCorrection&quot; FullName=&quot;ACS.WebDE.Edits.AddressCorrection&quot;&gt;&lt;LookupFields /&gt;&lt;ResultFields /&gt;&lt;/AddressCorrectionEditDef&gt;]]&gt;&lt;/EditDef&gt;
        ///&lt;EditDef DisplayName=&quot;CheckDigit&quot; FullName=&quot;WebDX.Api.Scripts.CheckDigitEdit&quot;&gt;&lt;![CDATA[&lt;CheckDigitEditDef DisplayName=&quot;CheckDigit&quot; FullName=&quot;WebDX.Api.Scripts.CheckDigitEdit&quot; /&gt;]]&gt;&lt;/EditDef&gt;
        ///&lt;EditDef DisplayName=&quot;ConditionalGoto&quot; F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditDefsWTXNew {
            get {
                return ResourceManager.GetString("EditDefsWTXNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EditDef DisplayName=&quot;DisplayName&quot; Description=&quot;Desc&quot; Enabled=&quot;True&quot; ErrorMessage=&quot;ErrorMessage&quot; ErrorType=&quot;WarningWithRetry&quot; SessionType=&quot;FullForm&quot; FullName=&quot;FullName&quot;&gt;&lt;![CDATA[&lt;AddressCorrectionEditDef DisplayName=&quot;AddressCorrection&quot; Enabled=&quot;True&quot; FullName=&quot;ACS.WebDE.Edits.AddressCorrection&quot; ReviewResults=&quot;True&quot; UseDPV=&quot;True&quot;&gt;
        ///  &lt;LookupFields CityField=&quot;Document1.Record1.Field1&quot; /&gt;
        ///  &lt;ResultFields StateField=&quot;Document1.Record1.Field2&quot; /&gt;
        ///&lt;/AddressCorrectionEditDef&gt;]]&gt;&lt;/EditDef&gt;.
        /// </summary>
        internal static string EditDefWTX {
            get {
                return ResourceManager.GetString("EditDefWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ScriptDef Description=&quot;SomeEvent&quot; Enabled=&quot;True&quot; ScriptFullName=&quot;Script.Full.Name&quot; /&gt;.
        /// </summary>
        internal static string EventScriptDefWTX {
            get {
                return ResourceManager.GetString("EventScriptDefWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDef CharSet=&quot;A-Z&quot; DataLen=&quot;10&quot; DataMask=&quot;DataMask&quot; DataType=&quot;DateTime&quot; DefaultValue=&quot;DefaultValue&quot; Description=&quot;Description&quot; OCRAllowedErrors=&quot;15&quot; OCRCharSet=&quot;Z-A&quot; OCRConfidence=&quot;75&quot; OCRRepairMode=&quot;AlphaNumeric&quot; Options=&quot;AllowFlag, MustComplete, UpperCase&quot; OCRName=&quot;OCRName&quot; OCRLine=&quot;2&quot; FieldTitle=&quot;FieldTitle&quot; FieldName=&quot;Field1&quot;&gt;
        ///  &lt;ScriptDef /&gt;
        ///&lt;/FieldDef&gt;
        ///&lt;FieldDef FieldName=&quot;Field2&quot;&gt;
        ///  &lt;ScriptDef /&gt;
        ///&lt;/FieldDef&gt;.
        /// </summary>
        internal static string FieldDefsWTX {
            get {
                return ResourceManager.GetString("FieldDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FormDef BackColor=&quot;Red&quot; Record=&quot;Document1.Record1&quot; DefaultImage=&quot;Document1.Image1&quot; Description=&quot;Description1&quot; Font=&quot;Arial, 12pt, style=Italic&quot; Help=&quot;Help1&quot; Hint=&quot;Hint1&quot; UseSnippets=&quot;True&quot; FormName=&quot;Form1&quot;&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt;ScriptDef /&gt;
        ///&lt;/FormDef&gt;
        ///&lt;FormDef Font=&quot;Tahoma, 10pt&quot; FormName=&quot;Form2&quot;&gt;
        ///  &lt;ScriptDef /&gt;
        ///  &lt;ScriptDef /&gt;
        ///&lt;/FormDef&gt;.
        /// </summary>
        internal static string FormDefsWTX {
            get {
                return ResourceManager.GetString("FormDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FormLink FormName=&quot;Document1.Form1&quot; /&gt;
        ///&lt;FormLink FormName=&quot;Document1.Form2&quot; /&gt;.
        /// </summary>
        internal static string FormLinksWTX {
            get {
                return ResourceManager.GetString("FormLinksWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ImageSourceDef ImageType=&quot;Image1&quot; StoredAttachType=&quot;StoredAttachType1&quot; Overlay=&quot;Overlay1&quot; Template=&quot;Template1&quot; PerformOCR=&quot;True&quot;&gt;
        ///  &lt;ZoneDef ZoneName=&quot;Zone1&quot; /&gt;
        ///  &lt;ZoneDef ZoneName=&quot;Zone2&quot; /&gt;
        ///  &lt;SnippetDef SnippetName=&quot;Snippet1&quot; /&gt;
        ///  &lt;SnippetDef SnippetName=&quot;Snippet2&quot; /&gt;
        ///  &lt;DetailZoneDef DetailZoneName=&quot;DetailZone1&quot; /&gt;
        ///  &lt;DetailZoneDef DetailZoneName=&quot;DetailZone2&quot; /&gt;
        ///&lt;/ImageSourceDef&gt;
        ///&lt;ImageSourceDef ImageType=&quot;Image2&quot; /&gt;.
        /// </summary>
        internal static string ImageSourceDefsWTX {
            get {
                return ResourceManager.GetString("ImageSourceDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LabelLink LabelName=&quot;Document1.Form1.Label1&quot; /&gt;
        ///&lt;LabelLink LabelName=&quot;Document1.Form1.Label2&quot; /&gt;.
        /// </summary>
        internal static string LabelLinksWriteToXml {
            get {
                return ResourceManager.GetString("LabelLinksWriteToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RecordDef Description=&quot;Description&quot; DesignRect=&quot;10,20,40,60&quot; RecType=&quot;Record1&quot; MaxRecs=&quot;50&quot; MinRecs=&quot;20&quot; /&gt;
        ///&lt;RecordDef RecType=&quot;Record2&quot; /&gt;.
        /// </summary>
        internal static string RecordDefsWTX {
            get {
                return ResourceManager.GetString("RecordDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RejectCode Name=&quot;01&quot; Description=&quot;BAD SCAN&quot; /&gt;
        ///&lt;RejectCode Name=&quot;02&quot; RequireDescription=&quot;True&quot; /&gt;.
        /// </summary>
        internal static string RejectCodesWTX {
            get {
                return ResourceManager.GetString("RejectCodesWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SessionDef Name=&quot;Session1&quot; DataPanelHeight=&quot;10&quot; FirstImage=&quot;1&quot; Options=&quot;AllowBatchReject, AllowFloatingWindow, ReviewAllImages, ShowWorkZones, ShowOverlay, AllowModifyNonKeyables, AllowDocReject, AutoSave, AllowImageTypeChange, AllowFieldVerify&quot; ShowTicker=&quot;True&quot; TickerCharHeight=&quot;15&quot; ImageScale=&quot;ScalePercent&quot; ImageScalePercent=&quot;50&quot; SessionType=&quot;NumericRepair&quot; SessionStyle=&quot;Vertical&quot;&gt;
        ///  &lt;PhotoStitchDef ColCount=&quot;3&quot; RowCount=&quot;3&quot; Orientation=&quot;Vertical&quot; /&gt;
        ///  &lt;FormLink FormName=&quot;Document1.Form1&quot; /&gt;
        ///  &lt;FormL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SessionDefsWTX {
            get {
                return ResourceManager.GetString("SessionDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleListEditDef List=&quot;ONE,TWO,THREE&quot; /&gt;.
        /// </summary>
        internal static string SimpleListWTX {
            get {
                return ResourceManager.GetString("SimpleListWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SnippetDef SnippetName=&quot;Snippet1&quot; SnippetRect=&quot;10,20,40,60&quot; /&gt;
        ///&lt;SnippetDef SnippetName=&quot;Snippet2&quot; /&gt;.
        /// </summary>
        internal static string SnippetDefsWTX {
            get {
                return ResourceManager.GetString("SnippetDefsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableLookupEditDef&gt;
        ///  &lt;TableLookup Database=&quot;Database1&quot; Query=&quot;Query1&quot; Options=&quot;FailIfNoRecords, ReviewResults, Filter, OneHitPopup, NullsToSpaces, LookupIfBlank, SavePos, ShowDiffs, VerifyPluggedData&quot;&gt;
        ///    &lt;LookupResultField DBFieldName=&quot;DBField1&quot; Field=&quot;Document1.Record1.Field1&quot; Options=&quot;Display, AllowFilter&quot; /&gt;
        ///    &lt;LookupResultField DBFieldName=&quot;DBField2&quot; Field=&quot;Document1.Record1.Field2&quot; /&gt;
        ///  &lt;/TableLookup&gt;
        ///  &lt;TableLookup Database=&quot;Database2&quot; Query=&quot;Query2&quot; /&gt;
        ///&lt;/TableLookupEditDef&gt;.
        /// </summary>
        internal static string TableLookupEditDefWTX {
            get {
                return ResourceManager.GetString("TableLookupEditDefWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ValidLengthsEditDef Lengths=&quot;1,2,3,4,5&quot; /&gt;.
        /// </summary>
        internal static string ValidLengthsWTX {
            get {
                return ResourceManager.GetString("ValidLengthsWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ZipCodeLookupEditDef Description=&quot;DESC&quot; Enabled=&quot;True&quot; ErrorMessage=&quot;ErrorMessage&quot; ErrorType=&quot;WarningWithRetry&quot; Options=&quot;CityCodeOverride, OneHitPopup, ReviewResults&quot; CityField=&quot;Document1.Record1.Field2&quot; CityCodeField=&quot;Document1.Record1.Field1&quot; StateField=&quot;Document1.Record1.Field3&quot; ZipCodeField=&quot;Document1.Record1.Field4&quot; /&gt;.
        /// </summary>
        internal static string ZipLookupWTX {
            get {
                return ResourceManager.GetString("ZipLookupWTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ZoneDef ZoneName=&quot;Zone1&quot; /&gt;
        ///&lt;ZoneDef ZoneName=&quot;Zone2&quot; /&gt;
        ///&lt;ZoneDef ZoneName=&quot;Zone3&quot; /&gt;.
        /// </summary>
        internal static string ZoneDefsWriteToXml {
            get {
                return ResourceManager.GetString("ZoneDefsWriteToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ZoneDef ZoneName=&quot;Zone1&quot; ZoneRect=&quot;10,20,40,60&quot; /&gt;.
        /// </summary>
        internal static string ZoneDefWriteToXml {
            get {
                return ResourceManager.GetString("ZoneDefWriteToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ZoneDefLink ZoneName=&quot;Document1.ImageType1.Zone1&quot; /&gt;
        ///&lt;ZoneDefLink ZoneName=&quot;Document1.ImageType1.Zone2&quot; /&gt;.
        /// </summary>
        internal static string ZoneLinksWriteToXml {
            get {
                return ResourceManager.GetString("ZoneLinksWriteToXml", resourceCulture);
            }
        }
    }
}
